[project]
name = "scenes"
platforms = ["linux-aarch64", "osx-arm64"]
channels = ["conda-forge"]

[dependencies]
python = "3.*"
pyyaml = "*"
pdbpp = "*"

[pypi-dependencies]
paho-mqtt = "*"
yamlcore = "*"

[tasks]
reset = "python ./reset.py"
config = "docker run --rm -it -v smarthome_zigbee2mqtt:/data -v $PWD:/source busybox /bin/sh"
