version: "3"

services:

  rsnapshot:
    image: lscr.io/linuxserver/rsnapshot:latest
    container_name: rsnapshot
    restart: always
    network_mode: bridge
    hostname: raspberry
    volumes:
      - rsnapshot:/config
      - /backup:/.snapshots
      - media_deluge:/data/media_deluge
      - media_radarr:/data/media_radarr
      - media_plex:/data/media_plex
      - monitor_diun:/data/monitor_diun
      - portainer:/data/portainer
      - smarthome_homebridge:/data/smarthome_homebridge
      - smarthome_mosquitto:/data/smarthome_mosquitto
      - smarthome_zigbee2mqtt:/data/smarthome_zigbee2mqtt
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"


volumes:
  rsnapshot:
  media_deluge:
    external: true
  media_radarr:
    external: true
  media_plex:
    external: true
  monitor_diun:
    external: true
  portainer:
    external: true
  smarthome_homebridge:
    external: true
  smarthome_mosquitto:
    external: true
  smarthome_zigbee2mqtt:
    external: true
