version: "3"

services:

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    hostname: mosquitto
    restart: always
    networks:
      - network
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - "mosquitto_data:/mosquitto/data"
      - "mosquitto_log:/mosquitto/log"
    command: "mosquitto -c /mosquitto-no-auth.conf"
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-t", "$$SYS/#", "-C", "1", "-i", "healthcheck", "-W", "3"]
      interval: 30s
      timeout: 2s
      retries: 5
      start_period: 30s
      start_interval: 5s
    environment:
      - "TZ=${TZ}"

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest
    container_name: zigbee2mqtt
    hostname: zigbee2mqtt
    restart: always
    networks:
      - network
    ports:
      - 8080:8080
    volumes:
      - "zigbee2mqtt:/app/data"
      - "/run/udev:/run/udev:ro"
    devices:
      - "/dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20231101144759-if00:/dev/ttyACM0"
    depends_on:
      mosquitto:
        condition: service_healthy
    healthcheck:
      test: wget --spider localhost:8080 || exit 1
      interval: 30s
      retries: 5
      timeout: 2s
      start_period: 30s
      start_interval: 5s
    environment:
      - "TZ=${TZ}"

  # Connection between zigbee server and Apple HomeKit
  homebridge:
    image: homebridge/homebridge:latest
    container_name: homebridge
    restart: always
    hostname: raspberry
    network_mode: host
    volumes:
      - "homebridge:/homebridge"
    depends_on:
      zigbee2mqtt:
        condition: service_healthy
    healthcheck:
      test: curl --fail localhost:8581 || exit 1
      interval: 30s
      retries: 5
      timeout: 5s
      start_period: 30s
      start_interval: 5s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "1"
    environment:
      - "TZ=${TZ}"

# Networks for smarthome services - allow services to be recognized by name
networks:
  network:
    driver: bridge

volumes:
  mosquitto_data:
  mosquitto_log:
  zigbee2mqtt:
  homebridge:
