version: "3"

services:

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    network_mode: bridge
    hostname: raspberry
    ports:
      - "192.168.1.6:53:53/tcp"
      - "192.168.1.6:53:53/udp"
      - "8001:8001/tcp"
    environment:
      - "TZ=${TZ}"
      - "WEBPASSWORD=${WEBPASSWORD}"
      - "WEBTHEME=default-auto"
      - "WEB_PORT=8001"
    volumes:
      - 'pihole_etc:/etc/pihole'
      - 'pihole_dnsmasq:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed

volumes:
  pihole_etc:
  pihole_dnsmasq:
