version: "3"

services:

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    hostname: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8001:8001/tcp"
    environment:
      - "TZ=${TZ}"
      - "WEBPASSWORD=${WEBPASSWORD}"
      - "WEBTHEME=default-auto"
      - "WEB_PORT=8001"
    volumes:
      - "pihole_etc:/etc/pihole"
      - "pihole_dnsmasq:/etc/dnsmasq.d"
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    networks:
      network:
        ipv4_address: "192.168.1.254"

# Networks for pihole - use a macvlan to get a new IP address,
# independently of the raspberry pi
networks:
  network:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: "192.168.1.0/24"
          ip_range: "192.168.1.0/24"
          gateway: "192.168.1.1"

volumes:
  pihole_etc:
  pihole_dnsmasq:
