version: "3"

services:

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    hostname: raspberry
    network_mode: host
    environment:
      - "TZ=${TZ}"
      - "WEBPASSWORD=${WEBPASSWORD}"
      - "WEBTHEME=default-auto"
      - "WEB_PORT=8001"
    volumes:
      - "pihole_etc:/etc/pihole"
      - "pihole_dnsmasq:/etc/dnsmasq.d"

volumes:
  pihole_etc:
  pihole_dnsmasq:
