[project]
name = "firmware-flasher"
platforms = ["linux-aarch64"]
channels = ["conda-forge"]

[dependencies]
python = "3.*"

[pypi-dependencies]
universal-silabs-flasher = "*"

[tasks]
flasher-coordinator = "universal-silabs-flasher --device /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20231101144759-if00"
flasher-router = "universal-silabs-flasher --device /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20231101081558-if00"
probe-coordinator = "universal-silabs-flasher --device /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20231101144759-if00 probe"
probe-router = "universal-silabs-flasher --device /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20231101081558-if00 probe"
flash-vendor-coordinator = "universal-silabs-flasher --device /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20231101144759-if00 flash --firmware ./ncp-uart-sw_EZNet6.10.3_V1.0.1.gbl"
flash-vendor-router = "universal-silabs-flasher --device /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20231101081558-if00 flash --firmware ./Z3RouterUSBDonlge_EZNet6.10.3_V1.0.0.gbl"
flash-nerivec-coordinator = "universal-silabs-flasher --device /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20231101144759-if00 flash --allow-cross-flashing --firmware ./sonoff_zbdonglee_zigbee_ncp_8.0.2.0_115200_sw_flow.gbl"
flash-nerivec-router = "universal-silabs-flasher --device /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20231101081558-if00 flash --force --firmware ./sonoff_zbdonglee_zigbee_router_8.0.2.0_115200_sw_flow.gbl"
